apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-jenkins
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jenkins
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-jenkins
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
    - name: agent
      port: 50000
      targetPort: 50000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-jenkins
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-jenkins
    spec:
      {{- with (default dict .Values.global).imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: jenkins
          image: "{{ (default dict .Values.global).imageRegistry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-jenkins
